### What is NumPy?

* Python library for creating N-dim arrays
* Ability to quickly broadcast functions
* Built-in linear algebra, stats, dist, trig, and random number capabilities

### Why use NumPy?

* much more efficient than Python lists
* apply functions to datasets very easily using broadcasting

### L14. NumPy Arrays

In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
type(my_list)

list

In [3]:
np.array(my_list)

array([1, 2, 3])

In [5]:
x = np.array(my_list)
x

array([1, 2, 3])

In [6]:
type(x)

numpy.ndarray

In [7]:
A = [[1,2,3], [4,5,6], [7,8,9]]

In [8]:
A

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
B = np.array(A)

In [10]:
B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
type(B)

numpy.ndarray

In [12]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [14]:
np.arange(0, 102, 2)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros((2,5))  # (rows, cols)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [20]:
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [21]:
np.linspace(0, 10, 11)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [22]:
np.linspace(0, 5, 21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [24]:
# identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Random Numbers

In [40]:
# uniform dist between [0,1)
np.random.rand(1)

array([0.37987438])

In [42]:
np.random.rand(5,2)

array([[0.24173234, 0.52199284],
       [0.96677996, 0.03065373],
       [0.08120264, 0.68831781],
       [0.69678424, 0.76895521],
       [0.91255403, 0.718844  ]])

In [43]:
# from standard normal dist
np.random.randn(10)

array([ 1.70399251,  1.33944298, -1.27160471,  0.67155769,  0.06252416,
        0.06222975, -0.05064896, -0.2563655 , -0.84917601,  0.56179377])

In [44]:
np.random.randn(2,3)

array([[-1.87816954,  0.14860597,  1.04907493],
       [ 0.2910694 , -0.87196322,  1.42005785]])

In [45]:
np.random.randint(0, 101, 5)  # uniform [5,101) 5 numbers

array([21, 29, 84, 39, 40])

In [46]:
# seed: to reproduce a particular set of random numbers
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [47]:
a = np.arange(0, 25)

In [48]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [49]:
a.reshape(5,5)  # reformat the array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
A = np.random.randint(0, 101, 10)
A

array([ 1, 87, 29, 37,  1, 63, 59, 20, 32, 75])

In [52]:
A.max()

87

In [53]:
A.min()

1

In [54]:
A.argmax()  # return the index of the max value

1

In [55]:
A.argmin()  # return the index of the min value

0

In [56]:
A.dtype

dtype('int32')

In [57]:
A.shape

(10,)

In [58]:
B = np.arange(0,25)

In [59]:
B

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [60]:
B.shape

(25,)

In [61]:
B.reshape(25, 1)  # reshape to a column

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [62]:
B.reshape(1, 25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

### L15: NumPy Indexing and Selection

In [63]:
a = np.arange(0, 11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [64]:
a[8]

8

In [65]:
a[1:5]  # up to but not including 5

array([1, 2, 3, 4])

In [66]:
a[:5]

array([0, 1, 2, 3, 4])

In [67]:
a[0:5]

array([0, 1, 2, 3, 4])

In [68]:
a[5:]

array([ 5,  6,  7,  8,  9, 10])

In [71]:
# broadcasting
a[:5] = 100
a

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [72]:
a = np.arange(0, 11)
array_slice = a[:5]   # THIS IS A POINTER TO ORIGINAL ARRAY A
array_slice

array([0, 1, 2, 3, 4])

In [73]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [74]:
array_slice[:] = 99

In [75]:
array_slice

array([99, 99, 99, 99, 99])

In [76]:
a

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [77]:
b = a.copy()
b

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [78]:
b[:] = 88

In [79]:
b


array([88, 88, 88, 88, 88, 88, 88, 88, 88, 88, 88])

In [80]:
a

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [81]:
A = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
A

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [82]:
A.shape  # returns rows by cols

(3, 3)

In [83]:
A[0]

array([ 5, 10, 15])

In [84]:
A[2]

array([35, 40, 45])

In [85]:
A[1][1]

25

In [86]:
A[1,1]

25

In [87]:
A[0,2]

15

In [88]:
# slicing
A[:2, 1:]

array([[10, 15],
       [25, 30]])

In [89]:
# conditional selection
a = np.arange(1, 11)

In [90]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
a > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [92]:
bool_array = (a > 4)

In [93]:
bool_array

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [94]:
a[bool_array]

array([ 5,  6,  7,  8,  9, 10])

In [95]:
a[a > 4]  # THIS IS VERY COMMON

array([ 5,  6,  7,  8,  9, 10])

### L16: NumPy Operations

In [99]:
a = np.arange(0, 10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
a + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [101]:
a - 2 

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [102]:
a + a

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [103]:
a - a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [104]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
a / a

<ipython-input-105-bb29898574ab>:1: RuntimeWarning: invalid value encountered in true_divide
  a / a


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [106]:
1 / 0

ZeroDivisionError: division by zero

In [107]:
1 / a

<ipython-input-107-0c5dc1e9adcb>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / a


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [108]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [109]:
np.log(a)

<ipython-input-109-89b6b8e53c58>:1: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [110]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [111]:
a.sum()

45

In [112]:
a.mean()

4.5

In [113]:
a.max()

9

In [114]:
a.var()

8.25

In [115]:
a.std()

2.8722813232690143

In [117]:
A = np.arange(0, 25).reshape(5,5)

In [118]:
A.shape

(5, 5)

In [119]:
A.sum()

300

In [120]:
A.sum(axis=0)  # rows are represented by axis=0
# perform sum of columns

array([50, 55, 60, 65, 70])

In [121]:
A.sum(axis=1)  # perform this operation across the rows

array([ 10,  35,  60,  85, 110])