In [1]:
import numpy as np

In [2]:
# scalars
c = 5
c

5

In [3]:
# vectors
x = np.array([5, -2, 4])
x

array([ 5, -2,  4])

In [5]:
# matrices
A = np.array([[5, 12, 6], [-3, 0, 14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [6]:
# data types
type(c)

int

In [7]:
# 1D array
type(x)

numpy.ndarray

In [8]:
# 2D array
type(A)

numpy.ndarray

In [9]:
s = np.array(c)
type(s)

numpy.ndarray

In [10]:
# data shapes
A.shape

(2, 3)

In [11]:
x.shape

(3,)

In [12]:
x.reshape(1,3)

array([[ 5, -2,  4]])

In [13]:
x.reshape(3,1)

array([[ 5],
       [-2],
       [ 4]])

In [15]:
c.shape

AttributeError: 'int' object has no attribute 'shape'

In [16]:
s.shape

()

### Tensors

In [17]:
m1 = np.array([[5, 12, 6], [-3, 0, 14]])

In [18]:
m2 = np.array([[9, 8, 7], [1, 3, -5]])

In [19]:
t = np.array([m1, m2])
t

array([[[ 5, 12,  6],
        [-3,  0, 14]],

       [[ 9,  8,  7],
        [ 1,  3, -5]]])

In [20]:
t.shape

(2, 2, 3)

In [21]:
# matrix addition
X = m1 + m2
X

array([[14, 20, 13],
       [-2,  3,  9]])

In [22]:
m1 - m2

array([[-4,  4, -1],
       [-4, -3, 19]])

In [26]:
a = np.array([[6,2], [-5,3], [4,-13]])
a

array([[  6,   2],
       [ -5,   3],
       [  4, -13]])

In [27]:
b = np.array([[2,-10], [9,3], [5,-2]])
b

array([[  2, -10],
       [  9,   3],
       [  5,  -2]])

In [28]:
a + b

array([[  8,  -8],
       [  4,   6],
       [  9, -15]])

In [29]:
a - b

array([[  4,  12],
       [-14,   0],
       [ -1, -11]])

In [30]:
# addition with scalars
a

array([[  6,   2],
       [ -5,   3],
       [  4, -13]])

In [31]:
a + 1

array([[  7,   3],
       [ -4,   4],
       [  5, -12]])

In [32]:
x = np.array([1, 2, 3, 4, 5])
x + 100

array([101, 102, 103, 104, 105])

In [33]:
# Python allows us to add a scalar to a matrix or vector using the built-in BROADCAST ability

In [34]:
a

array([[  6,   2],
       [ -5,   3],
       [  4, -13]])

In [35]:
a.T

array([[  6,  -5,   4],
       [  2,   3, -13]])

In [36]:
B = np.array([[5,3], [-2,4]])
B

array([[ 5,  3],
       [-2,  4]])

In [37]:
B.T

array([[ 5, -2],
       [ 3,  4]])

In [38]:
s.T

array(5)

In [39]:
# transposing vectors
x

array([1, 2, 3, 4, 5])

In [40]:
# no change to shape:
x.T

array([1, 2, 3, 4, 5])

In [41]:
x.shape

(5,)

In [42]:
# we can use reshape if we want to convert the row/column vector to a column/row:
y = x.reshape(1,5)
y

array([[1, 2, 3, 4, 5]])

In [45]:
y.T

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [46]:
# inner product: DOT PRODUCT or SCALAR PRODUCT
x = np.array([2, 8, -4])
y = np.array([1, -7, 3])

In [47]:
np.dot(x, y)

-66

In [48]:
np.dot(5, 6)

30

In [50]:
# scaling a vector by a constant (scalar)
5 * x

array([ 10,  40, -20])

In [52]:
A = np.array([[5, 12, 6], [-3, 0, 14]])
A

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [53]:
3 * A

array([[15, 36, 18],
       [-9,  0, 42]])

In [54]:
B = np.array([[2, 1], [8, 0], [3, 0]])
B

array([[2, 1],
       [8, 0],
       [3, 0]])

In [55]:
np.dot(A, B)

array([[124,   5],
       [ 36,  -3]])